use_frameworks!

platform :ios, '9.0'

target 'YCocoaTest_Example' do
  pod 'YCocoaTest', :path => '../'

  target 'YCocoaTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
